/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.12
 * Generated at: 2020-08-13 08:13:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.page;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class realtime_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/pf.tld", Long.valueOf(1596463248000L));
    _jspx_dependants.put("/WEB-INF/gis.tld", Long.valueOf(1596463248000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpf_005fhead_0026_005ftitle;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgis_005fhead_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpf_005fbody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpf_005fdataGrid_0026_005furl_005fstyle_005fpageSize_005fonrowclick_005finitLoad_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgis_005fmap_0026_005fonload_005fmapCode_005fid_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgis_005fpop_0026_005fskin_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fgis_005fscript;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpf_005fscript;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpf_005fhead_0026_005ftitle = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgis_005fhead_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpf_005fbody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpf_005fdataGrid_0026_005furl_005fstyle_005fpageSize_005fonrowclick_005finitLoad_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgis_005fmap_0026_005fonload_005fmapCode_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgis_005fpop_0026_005fskin_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fgis_005fscript = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fpf_005fscript = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fpf_005fhead_0026_005ftitle.release();
    _005fjspx_005ftagPool_005fgis_005fhead_005fnobody.release();
    _005fjspx_005ftagPool_005fpf_005fbody.release();
    _005fjspx_005ftagPool_005fpf_005fdataGrid_0026_005furl_005fstyle_005fpageSize_005fonrowclick_005finitLoad_005fid.release();
    _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield.release();
    _005fjspx_005ftagPool_005fgis_005fmap_0026_005fonload_005fmapCode_005fid_005fnobody.release();
    _005fjspx_005ftagPool_005fgis_005fpop_0026_005fskin_005fid.release();
    _005fjspx_005ftagPool_005fgis_005fscript.release();
    _005fjspx_005ftagPool_005fpf_005fscript.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_pf_005fhead_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#gis-pop-stand2-search-combox input{\r\n");
      out.write("\t\theight: 38px;\r\n");
      out.write("\t\tline-height:38px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      if (_jspx_meth_pf_005fbody_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_pf_005fhead_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:head
    com.yuantiao.webplatform.ui.base.HeadTag _jspx_th_pf_005fhead_005f0 = (com.yuantiao.webplatform.ui.base.HeadTag) _005fjspx_005ftagPool_005fpf_005fhead_0026_005ftitle.get(com.yuantiao.webplatform.ui.base.HeadTag.class);
    boolean _jspx_th_pf_005fhead_005f0_reused = false;
    try {
      _jspx_th_pf_005fhead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fhead_005f0.setParent(null);
      // /WEB-INF/jsp/page/realtime.jsp(8,0) name = title type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fhead_005f0.setTitle((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_pf_005fhead_005f0 = _jspx_th_pf_005fhead_005f0.doStartTag();
      if (_jspx_eval_pf_005fhead_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fhead_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fhead_005f0);
        }
        do {
          out.write('\r');
          out.write('\n');
          out.write('	');
          if (_jspx_meth_gis_005fhead_005f0(_jspx_th_pf_005fhead_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_pf_005fhead_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fhead_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fhead_0026_005ftitle.reuse(_jspx_th_pf_005fhead_005f0);
      _jspx_th_pf_005fhead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fhead_005f0, _jsp_getInstanceManager(), _jspx_th_pf_005fhead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_gis_005fhead_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fhead_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gis:head
    com.yuantiao.webplatform.gis.tag.HeadTag _jspx_th_gis_005fhead_005f0 = (com.yuantiao.webplatform.gis.tag.HeadTag) _005fjspx_005ftagPool_005fgis_005fhead_005fnobody.get(com.yuantiao.webplatform.gis.tag.HeadTag.class);
    boolean _jspx_th_gis_005fhead_005f0_reused = false;
    try {
      _jspx_th_gis_005fhead_005f0.setPageContext(_jspx_page_context);
      _jspx_th_gis_005fhead_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fhead_005f0);
      int _jspx_eval_gis_005fhead_005f0 = _jspx_th_gis_005fhead_005f0.doStartTag();
      if (_jspx_th_gis_005fhead_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fgis_005fhead_005fnobody.reuse(_jspx_th_gis_005fhead_005f0);
      _jspx_th_gis_005fhead_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_gis_005fhead_005f0, _jsp_getInstanceManager(), _jspx_th_gis_005fhead_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_pf_005fbody_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:body
    com.yuantiao.webplatform.ui.base.BodyTag _jspx_th_pf_005fbody_005f0 = (com.yuantiao.webplatform.ui.base.BodyTag) _005fjspx_005ftagPool_005fpf_005fbody.get(com.yuantiao.webplatform.ui.base.BodyTag.class);
    boolean _jspx_th_pf_005fbody_005f0_reused = false;
    try {
      _jspx_th_pf_005fbody_005f0.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fbody_005f0.setParent(null);
      int _jspx_eval_pf_005fbody_005f0 = _jspx_th_pf_005fbody_005f0.doStartTag();
      if (_jspx_eval_pf_005fbody_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fbody_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fbody_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t<div style=\"width: 100%; height: 100%; overflow: auto;\">\r\n");
          out.write("\t\t<div style=\"width: 100%; height: 100%;\">\r\n");
          out.write("\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\tstyle=\"position: relative; float: left; overflow: hidden; width: 1920px; height: 1080px; display: block; background: transparent;\">\r\n");
          out.write("\t\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\t\tstyle=\"position: relative; float: left; width: 100%; height: 100%; overflow-y: hidden;\">\r\n");
          out.write("\t\t\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"position: relative; float: left; overflow: hidden auto; width: 200px; height: 100%; display: block;\">\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_pf_005fdataGrid_005f0(_jspx_th_pf_005fbody_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\t\t\tstyle=\"position: relative; float: left; overflow: hidden auto; width: 1720px; height: 100%; display: block;\">\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t<!-- put the map here -->\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_gis_005fmap_005f0(_jspx_th_pf_005fbody_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_gis_005fpop_005f0(_jspx_th_pf_005fbody_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 99; top: 759px; left: 1025px; width: 200px; height: 100px;\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"yt-dataView-content\"\r\n");
          out.write("\t\t\t\t\t\t\t\tstyle=\"position: relative; width: 100%; height: 100%; overflow: hidden;\">\r\n");
          out.write("\t\t\t\t\t\t\t\tD</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"\"\r\n");
          out.write("\t\t\t\t\t\t\tstyle=\"position: absolute; z-index: 99; top: 19px; left: 986px; width: 200px; height: 100px;\">\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"yt-dataView-content\"\r\n");
          out.write("\t\t\t\t\t\t\t\tstyle=\"position: relative; width: 100%; height: 100%; overflow: hidden;\">\r\n");
          out.write("\t\t\t\t\t\t\t\tE</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</div>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\t</div>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_gis_005fscript_005f0(_jspx_th_pf_005fbody_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t");
          if (_jspx_meth_pf_005fscript_005f0(_jspx_th_pf_005fbody_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_pf_005fbody_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fbody_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fbody_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fbody.reuse(_jspx_th_pf_005fbody_005f0);
      _jspx_th_pf_005fbody_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fbody_005f0, _jsp_getInstanceManager(), _jspx_th_pf_005fbody_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_pf_005fdataGrid_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fbody_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:dataGrid
    com.yuantiao.webplatform.ui.lists.DataGridTag _jspx_th_pf_005fdataGrid_005f0 = (com.yuantiao.webplatform.ui.lists.DataGridTag) _005fjspx_005ftagPool_005fpf_005fdataGrid_0026_005furl_005fstyle_005fpageSize_005fonrowclick_005finitLoad_005fid.get(com.yuantiao.webplatform.ui.lists.DataGridTag.class);
    boolean _jspx_th_pf_005fdataGrid_005f0_reused = false;
    try {
      _jspx_th_pf_005fdataGrid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fdataGrid_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fbody_005f0);
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setId("datagrid");
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = url type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setUrl("/dataengine/api/getGridData?interfaceCode=road");
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = style type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setStyle("width: 100%; height: 100%");
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = initLoad type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setInitLoad(new java.lang.Boolean(true));
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = pageSize type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setPageSize("50");
      // /WEB-INF/jsp/page/realtime.jsp(27,6) name = onrowclick type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fdataGrid_005f0.setOnrowclick("datagridClick");
      int _jspx_eval_pf_005fdataGrid_005f0 = _jspx_th_pf_005fdataGrid_005f0.doStartTag();
      if (_jspx_eval_pf_005fdataGrid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fdataGrid_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fdataGrid_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_pf_005fcolumn_005f0(_jspx_th_pf_005fdataGrid_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          if (_jspx_meth_pf_005fcolumn_005f1(_jspx_th_pf_005fdataGrid_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_pf_005fdataGrid_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fdataGrid_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fdataGrid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fdataGrid_0026_005furl_005fstyle_005fpageSize_005fonrowclick_005finitLoad_005fid.reuse(_jspx_th_pf_005fdataGrid_005f0);
      _jspx_th_pf_005fdataGrid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fdataGrid_005f0, _jsp_getInstanceManager(), _jspx_th_pf_005fdataGrid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_pf_005fcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fdataGrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:column
    com.yuantiao.webplatform.ui.lists.ColumnsTag _jspx_th_pf_005fcolumn_005f0 = (com.yuantiao.webplatform.ui.lists.ColumnsTag) _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield.get(com.yuantiao.webplatform.ui.lists.ColumnsTag.class);
    boolean _jspx_th_pf_005fcolumn_005f0_reused = false;
    try {
      _jspx_th_pf_005fcolumn_005f0.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fdataGrid_005f0);
      // /WEB-INF/jsp/page/realtime.jsp(28,7) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fcolumn_005f0.setField("road_code");
      int _jspx_eval_pf_005fcolumn_005f0 = _jspx_th_pf_005fcolumn_005f0.doStartTag();
      if (_jspx_eval_pf_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fcolumn_005f0);
        }
        do {
          out.write("路段编码");
          int evalDoAfterBody = _jspx_th_pf_005fcolumn_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield.reuse(_jspx_th_pf_005fcolumn_005f0);
      _jspx_th_pf_005fcolumn_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fcolumn_005f0, _jsp_getInstanceManager(), _jspx_th_pf_005fcolumn_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_pf_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fdataGrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:column
    com.yuantiao.webplatform.ui.lists.ColumnsTag _jspx_th_pf_005fcolumn_005f1 = (com.yuantiao.webplatform.ui.lists.ColumnsTag) _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield.get(com.yuantiao.webplatform.ui.lists.ColumnsTag.class);
    boolean _jspx_th_pf_005fcolumn_005f1_reused = false;
    try {
      _jspx_th_pf_005fcolumn_005f1.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fdataGrid_005f0);
      // /WEB-INF/jsp/page/realtime.jsp(29,7) name = field type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_pf_005fcolumn_005f1.setField("road_name");
      int _jspx_eval_pf_005fcolumn_005f1 = _jspx_th_pf_005fcolumn_005f1.doStartTag();
      if (_jspx_eval_pf_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fcolumn_005f1);
        }
        do {
          out.write("路段名称");
          int evalDoAfterBody = _jspx_th_pf_005fcolumn_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fcolumn_0026_005ffield.reuse(_jspx_th_pf_005fcolumn_005f1);
      _jspx_th_pf_005fcolumn_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fcolumn_005f1, _jsp_getInstanceManager(), _jspx_th_pf_005fcolumn_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_gis_005fmap_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fbody_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gis:map
    com.yuantiao.webplatform.gis.tag.MapTag _jspx_th_gis_005fmap_005f0 = (com.yuantiao.webplatform.gis.tag.MapTag) _005fjspx_005ftagPool_005fgis_005fmap_0026_005fonload_005fmapCode_005fid_005fnobody.get(com.yuantiao.webplatform.gis.tag.MapTag.class);
    boolean _jspx_th_gis_005fmap_005f0_reused = false;
    try {
      _jspx_th_gis_005fmap_005f0.setPageContext(_jspx_page_context);
      _jspx_th_gis_005fmap_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fbody_005f0);
      // /WEB-INF/jsp/page/realtime.jsp(36,6) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_gis_005fmap_005f0.setId("map");
      // /WEB-INF/jsp/page/realtime.jsp(36,6) name = mapCode type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_gis_005fmap_005f0.setMapCode("barrett");
      // /WEB-INF/jsp/page/realtime.jsp(36,6) name = onload type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_gis_005fmap_005f0.setOnload("mapload");
      int _jspx_eval_gis_005fmap_005f0 = _jspx_th_gis_005fmap_005f0.doStartTag();
      if (_jspx_th_gis_005fmap_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fgis_005fmap_0026_005fonload_005fmapCode_005fid_005fnobody.reuse(_jspx_th_gis_005fmap_005f0);
      _jspx_th_gis_005fmap_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_gis_005fmap_005f0, _jsp_getInstanceManager(), _jspx_th_gis_005fmap_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_gis_005fpop_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fbody_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gis:pop
    com.yuantiao.webplatform.gis.tag.PopTag _jspx_th_gis_005fpop_005f0 = (com.yuantiao.webplatform.gis.tag.PopTag) _005fjspx_005ftagPool_005fgis_005fpop_0026_005fskin_005fid.get(com.yuantiao.webplatform.gis.tag.PopTag.class);
    boolean _jspx_th_gis_005fpop_005f0_reused = false;
    try {
      _jspx_th_gis_005fpop_005f0.setPageContext(_jspx_page_context);
      _jspx_th_gis_005fpop_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fbody_005f0);
      // /WEB-INF/jsp/page/realtime.jsp(37,6) name = skin type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_gis_005fpop_005f0.setSkin("stand2");
      // /WEB-INF/jsp/page/realtime.jsp(37,6) name = id type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_gis_005fpop_005f0.setId("pop");
      int _jspx_eval_gis_005fpop_005f0 = _jspx_th_gis_005fpop_005f0.doStartTag();
      if (_jspx_eval_gis_005fpop_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_gis_005fpop_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_gis_005fpop_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_gis_005fpop_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_gis_005fpop_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_gis_005fpop_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fgis_005fpop_0026_005fskin_005fid.reuse(_jspx_th_gis_005fpop_005f0);
      _jspx_th_gis_005fpop_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_gis_005fpop_005f0, _jsp_getInstanceManager(), _jspx_th_gis_005fpop_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_gis_005fscript_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fbody_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  gis:script
    com.yuantiao.webplatform.gis.tag.ScriptTag _jspx_th_gis_005fscript_005f0 = (com.yuantiao.webplatform.gis.tag.ScriptTag) _005fjspx_005ftagPool_005fgis_005fscript.get(com.yuantiao.webplatform.gis.tag.ScriptTag.class);
    boolean _jspx_th_gis_005fscript_005f0_reused = false;
    try {
      _jspx_th_gis_005fscript_005f0.setPageContext(_jspx_page_context);
      _jspx_th_gis_005fscript_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fbody_005f0);
      int _jspx_eval_gis_005fscript_005f0 = _jspx_th_gis_005fscript_005f0.doStartTag();
      if (_jspx_eval_gis_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_gis_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_gis_005fscript_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\t\tfunction mapload(){\r\n");
          out.write("\t\t\tYTMapUtil.showLayer(\"crossLayer\",null);\r\n");
          out.write("\t\t\tYTMapUtil.showLayer(\"areaLayer\",null);\t\r\n");
          out.write("\t\t\tYTMapUtil.showLayer(\"roadLayer\",null);\t\r\n");
          out.write("\t\t}\r\n");
          out.write("\t\tYTMapUtil.setCustomPopwinShow(function(code,pop,clickData,popModule){\r\n");
          out.write("\t\t\t\t$(\".gis-pop-stand2-detail\").css(\"display\",\"block\");\r\n");
          out.write("\t\t\t\tpf.get(\"gis-pop-stand2-detail-panel\").setUrl(pop.url);\r\n");
          out.write("\t\t\t\tpf.get(\"gis-pop-stand2-search-combox\").setShowClose(true)\r\n");
          out.write("\t\t})\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_gis_005fscript_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_gis_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_gis_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fgis_005fscript.reuse(_jspx_th_gis_005fscript_005f0);
      _jspx_th_gis_005fscript_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_gis_005fscript_005f0, _jsp_getInstanceManager(), _jspx_th_gis_005fscript_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_pf_005fscript_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_pf_005fbody_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  pf:script
    com.yuantiao.webplatform.ui.base.ScriptTag _jspx_th_pf_005fscript_005f0 = (com.yuantiao.webplatform.ui.base.ScriptTag) _005fjspx_005ftagPool_005fpf_005fscript.get(com.yuantiao.webplatform.ui.base.ScriptTag.class);
    boolean _jspx_th_pf_005fscript_005f0_reused = false;
    try {
      _jspx_th_pf_005fscript_005f0.setPageContext(_jspx_page_context);
      _jspx_th_pf_005fscript_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_pf_005fbody_005f0);
      int _jspx_eval_pf_005fscript_005f0 = _jspx_th_pf_005fscript_005f0.doStartTag();
      if (_jspx_eval_pf_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_pf_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_pf_005fscript_005f0);
        }
        do {
          out.write("\r\n");
          out.write("\tfunction datagridClick(e){\r\n");
          out.write("\t\tYTMapUtil.triggerEvent(\"click\",\"roadLayer\",\"ROAD_CODE\",e.rocord.road_code);\r\n");
          out.write("\t\tYTMapUtil.setCenter(e.record.lng, e.record.lat);\r\n");
          out.write("\t}\r\n");
          out.write("\t\r\n");
          out.write("\tvar combox = pf.get(\"gis-pop-stand2-search-combox\");\r\n");
          out.write("\tcombox.load(\"/dataengine/api/getGridData?interfaceCode=road\");\r\n");
          out.write("\tcombox.setValueField(\"road_code\");\r\n");
          out.write("\tcombox.setTextField(\"road_name\");\r\n");
          out.write("\tcombox.on(\"itemClick\", function(e){\r\n");
          out.write("\t\tYTMapUtil.triggerEvent(\"click\",\"roadLayer\",\"ROAD_CODE\",e.item.road_code);\r\n");
          out.write("\t\tYTMapUtil.setCenter(e.item.lng, e.item.lat);\r\n");
          out.write("\t});\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_pf_005fscript_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_pf_005fscript_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_pf_005fscript_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fpf_005fscript.reuse(_jspx_th_pf_005fscript_005f0);
      _jspx_th_pf_005fscript_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_pf_005fscript_005f0, _jsp_getInstanceManager(), _jspx_th_pf_005fscript_005f0_reused);
    }
    return false;
  }
}
